// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculator.Data;

#nullable disable

namespace TaxCalculator.API.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxCalculator.Domain.Models.TaxBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BandName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("LowerLimit")
                        .HasColumnType("int");

                    b.Property<int>("TaxRate")
                        .HasColumnType("int");

                    b.Property<int?>("UpperLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaxBands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13c9c3cd-ea43-447d-a563-9908837f86ba"),
                            BandName = "TaxBandA",
                            LowerLimit = 0,
                            TaxRate = 0,
                            UpperLimit = 5000
                        },
                        new
                        {
                            Id = new Guid("049ad191-2b58-4864-ab00-026a789163a0"),
                            BandName = "TaxBandB",
                            LowerLimit = 5000,
                            TaxRate = 20,
                            UpperLimit = 20000
                        },
                        new
                        {
                            Id = new Guid("7c5e4143-a4ce-4c1c-aa8e-a727a01d7c68"),
                            BandName = "TaxBandC",
                            LowerLimit = 20000,
                            TaxRate = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
